include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.main.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

variables:
  MYSQL_DATABASE: "drupal"
  MYSQL_USER: "drupaltestbot"
  MYSQL_PASSWORD: "drupaltestbotpw"
  MYSQL_ROOT_PASSWORD: "root"
  FF_NETWORK_PER_BUILD: "1"
  SKIP_ESLINT: '1'
  SKIP_CSPELL: '1'
  SKIP_STYLELINT: '1'
  _WEB_ROOT: 'alternative-name'
  _SHOW_ENVIRONMENT_VARIABLES: 1
  _PHPCS_EXTRA: '--ignore=tests/*'

composer:
  extends: .composer-base
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends $PHPIZE_DEPS php-imagick imagemagick libmagickwand-dev
    - pecl install imagick
    - docker-php-ext-enable imagick
  variables:
    DRUPAL_CORE: "11.1.8"
  script:
    - composer install --no-progress --prefer-dist --optimize-autoloader --ignore-platform-reqs
  artifacts:
    paths:
      - vendor/
      - composer.lock
    expire_in: 1 day

tests:
  stage: test
  dependencies: []
  image: drupalci/php-8.3-ubuntu-apache:production
  services:
    - name: 'drupalci/mysql-8'
      alias: database
    - name: selenium/standalone-chrome:latest
      alias: selenium
  variables:
    _WEB_ROOT: 'web'
    SIMPLETEST_DB: "mysql://drupaltestbot:drupaltestbotpw@database/drupal"
    SIMPLETEST_BASE_URL: "http://web"
  script:
    - apt-get update -yqq
    - apt-get install -yqq wget unzip curl gnupg default-mysql-client xvfb libmagickwand-dev imagemagick jq
    - ln -sf /dev/null /var/log/apache2/access.log
    - pecl install imagick
    - docker-php-ext-enable imagick
    - php -m | grep imagick || { echo "Imagick not loaded!"; exit 1; }

    - mkdir -p web/themes/custom/ || true
    - cp -r starter-theme/openintranet_theme web/themes/custom/ || echo "Starter theme missing, skipping"

    - composer install --no-progress --prefer-dist --optimize-autoloader --ignore-platform-reqs

    - mkdir -p /var/www/html
    - ln -sf ${CI_PROJECT_DIR} /var/www/html/
    - ln -sf ${CI_PROJECT_DIR}/web /var/www/html/web
    - php -S 0.0.0.0:80 -t web/ > /dev/null 2>&1 &
    - sleep 2
    - echo "127.0.0.1 web" >> /etc/hosts

    - mysql -h database -u drupaltestbot -pdrupaltestbotpw -e "CREATE DATABASE IF NOT EXISTS drupal;"

    - cp web/sites/default/default.settings.php web/sites/default/settings.php
    - echo "\$databases['default']['default'] = [
      'database' => 'drupal',
      'username' => 'drupaltestbot',
      'password' => 'drupaltestbotpw',
      'prefix' => '',
      'host' => 'database',
      'port' => '3306',
      'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
      'driver' => 'mysql',
      ];" >> web/sites/default/settings.php
    - echo "\$settings['hash_salt'] = 'dummy-salt-for-ci-tests-replace-me-later';" >> web/sites/default/settings.php
    - mkdir -p web/sites/default/files && chmod -R 777 web/sites/default/files
    - echo "\$config['system.performance']['css']['preprocess'] = FALSE;" >> web/sites/default/settings.php
    - echo "\$config['system.performance']['js']['preprocess'] = FALSE;" >> web/sites/default/settings.php

    - ./vendor/bin/drush site-install openintranet install_configure_form.enable_demo_content=1 --account-name=admin --account-pass=admin --site-name="Open Intranet CI" -y
    - ./vendor/bin/drush cr

    - ./vendor/bin/codecept build
    - ./vendor/bin/codecept run Acceptance --xml --env gitlab
    - ./vendor/bin/codecept run JsCapable --xml --env gitlab

  artifacts:
    when: always
    paths:
      - tests/_output/
      - web/sites/default/settings.php
    expire_in: 1 day
