include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.main.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

variables:
  MYSQL_DATABASE: "drupal"
  MYSQL_USER: "drupaltestbot"
  MYSQL_PASSWORD: "drupaltestbotpw"
  MYSQL_ROOT_PASSWORD: "root"
  FF_NETWORK_PER_BUILD: "1"
  SKIP_ESLINT: '1'
  SKIP_CSPELL: '1'
  SKIP_STYLELINT: '1'
  _WEB_ROOT: 'alternative-name'
  _SHOW_ENVIRONMENT_VARIABLES: 1
  _PHPCS_EXTRA: '--ignore=tests/*'

composer:
  extends: .composer-base
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends $PHPIZE_DEPS php-imagick imagemagick libmagickwand-dev
    - pecl install imagick
    - docker-php-ext-enable imagick
  variables:
    DRUPAL_CORE: "11.1.8"
  script:
    - composer install --no-progress --prefer-dist --optimize-autoloader --ignore-platform-reqs
  artifacts:
    paths:
      - vendor/
      - composer.lock
    expire_in: 1 day
